version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "conda"
    target-branch: "dependabot-conda-live"
    directory: "devtools/conda-envs/"
    patterns: ["test*ml"]
    schedule:
      interval: "cron"
      cronjob: "0 * * * *"
