version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "conda"
    target-branch: "dependabot-conda-live"
    directory: "/"
    patterns: ["**/*.yaml", "**/*.yml"]
    schedule:
      interval: "daily"
